### ISSUE TITLE
1.7.10 It wont work? 

### ISSUE THREAD

**Issue by Radixy** [Th3Tr0LLeR/SkinsRestorer---Maro#108]
First of all...
I'd like to thank you for the great mod/plugin, though, I suspect the plugin is incompatible with my 1.7.10 server. 

I was wondering if that's the case or if I've done something wrong? I've tried downloading all the latest versions aswell as the old ones but neither seem to work. I keep getting a load of errors and yeah...

Should I post the errors or?

**Comment by Blackfire62** [comment]
I dropped supporting versions below 1.8 . Since 1.8 there was a pretty big rewrite of some stuff like packets and skins and adding support to version below 1.8 would mean quite some time invested in making it.

I said if a lot of people request it,i might do it, but otherwise its just not wroth, because no one plays that version anymore .

**Comment by Radixy** [comment]
D'aw, I would've donated though, but alright, I respect your decision! :)

I hope more people will request it more often soon. :) :+1:

**Comment by Th3Tr0LLeR** [comment]
Btw already working for 1.7 :dancer:

**Comment by k1r0s** [comment]
@Th3Tr0LLeR where do I can find the jar, or rather compiling instructions? thx
