### ISSUE TITLE
SkinRestorer Discconect Error

### ISSUE THREAD

**Issue by GhosTReis46** [Th3Tr0LLeR/SkinsRestorer---Maro#174]
installed the plugin but I get a connection error when I enter the game

**Comment by GhosTReis46** [comment]
Help me

**Comment by 030Amber** [comment]
There's really a bug about this. When a player join my server, random 5~10 players disconnect with "indexoutofbounds" exception, while on the server side it seems it's a normal disconnect. Really frustrating bug.

**Comment by Eredrim** [comment]
This the complete error. Please correct this bug quickly, it is blocking.

`Internal Exception: io.netty.handler.coder.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(971) + length(1) exceeds writerIndex(971): UnpooledHeapByteBuf(ridx: 971, widx: 971, cap: 971/971)`

**Comment by PinoyLifeCraft** [comment]
Me to ! I get that Annoying DC :disappointed: 
First, I thought it was the Holographic Displays Plugin problem because in there Update it said that ~Fixed disconnect error with ProtocolLib when hiding and showing a hologram to a player....
Till I found this issue in SkinRestorer Hope it will fix :+1:

**Comment by Eredrim** [comment]
Corrected in the latest version for me (v1.9.5).

**Comment by xknat** [comment]
for support, join our discord support server! [https://discord.me/skinsrestorer](https://discord.me/skinsrestorer)
