### ISSUE TITLE
Mysql connection spam

### ISSUE THREAD

**Issue by MorkaZ** [Th3Tr0LLeR/SkinsRestorer---Maro#222]
This plugin is overloading mysql server with connections, when ping is a little bigger or when there is 1 fail attemp.
Sending next 1000 connections is really bad.
It is not better to make asynchronous/synchronous clock with loop that will try to connect, for example, every 4 seconds?

Example with 200ms:
https://pastebin.com/vtABiewt
Better fix this. My other servers on the same IP did not connect to mysql because this plugin spammed a lot.

**Comment by DoNotSpamPls** [comment]
@piter909 we are reworking MySQL connections for the next version of SkinsRestorer. Your issue is that there are too many active connections to the MySQL server, if you stop some connections it should be fixed.

**Comment by piter909** [comment]
It is because, before it connects and got return, it sent thousands of mysql connections requests - not queries! (scroll down, there are many successfull connections). As I see this is mix of result of connections that have been sent in the same moment, not from newest to oldest.
And I know how to fix too many connections, I do not have to restart mysql, it has cooldown.. But this plugin is the source of this problem.

**Comment by DoNotSpamPls** [comment]
Hey there,
We'd love to get some help on the MySQL issue. 
If you'd like to help, you can visit us on our [Discord](https://discord.me/skinsrestorer)

**Comment by DoNotSpamPls** [comment]
@piter909
